name: Build Docker image

# Run workflow on PRs and pushes to matching branches
on:  # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  pull_request:

jobs:
  build_image:
    name: Build Docker image (no push)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          push: false
