---
name: Lint code

# Run workflow on PRs and pushes to matching branches
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:

jobs:
  lint_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install hatch
        run: pip install hatch

      - name: Test Python
        run: hatch run lint:all
